import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

import { RobanaDetailsPage } from '../page';
/**
 * Generated class for the RobanaPage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-robana',
  templateUrl: 'robana.html',
})
export class RobanaPage {

  hadith: Array<{id: any, name: string, note: string, explanation: string }>;

  constructor(public navCtrl: NavController, public navParams: NavParams) {
    this.hadith = [];
    this.hadith.push(
    {id: 1,  name: "Hadith 1", note: "Deed depends on intention", explanation: "On the authority of chief of the believers, Abu Hafs 'umar ibn al-khattab (R.A) who said: I heard the messenger of Allah (S.A.W) saying: The rewards of deeds depends on intentions and every person will get reward according to he has intended. Thus he whose migration was for Allah and his messenger, his migration was for Allah and his messenger, and he whoses migration was to achieve some wordly benefit or to take some woman in marriage, his migration was for that which he migrated. "},
    {id: 2,  name: "Hadith 2", note: "Explanation on Islam, iman and ihsan", explanation: "On the authority of umar ibn khattab (R.A) who said: One day while we sitting with the messenger of Allah (S.A.W) there appeared before us a man whose clothes exceedingly white and whose hair exceedingly black; no signs of journeying were to be seen on him and none of us knew him. He walked up and sat down by the prophet (S.A.W) resting his knees against his and placing palms of his hand on his thighs, then he said: O Muhammad, tell me about islam. The messengerof Allah (S.A.W) said: islam is to testify that there is no god to be worshipped but Allah ana that the Muhammad is the messenger of Allah, to pay the Zakat, to perform the prayers, to fast in Ramadan, and to make the pilgrimage to the house (ka'abah in makka) if you are able to do so. He said: you have spoken rightly, and we were amazed at him, asking him and saying that he had spoken rightly. He said: then tell me about ihman. He siad it is to believe in Allah, His angels, His books, His messengers, and the last day, and to believe in divine destiny (preordainment), both the good and the evil thereof. H said: You have spoken rightly. He said:Then tell me abbout ihsan. He said: It is to worship Allah as though you are seeing him, and while you see him not yet truly He sees you.    He said, Inform me about the Hour.He (the Messenger of Allah) said, About that, the one questioned knows no more than the questioner. So he said, Well, inform me about the signs thereof. He said, They are that the slave-girl will give birth to her mistress, that you will see the barefooted, naked, destitute, the herdsmen of the sheep (competing with each other) in raising lofty buildings.Thereupon the man went off. I waited a while, and then he (the Messenger of Allah) said, O Umar, do you know who that questioner was? I replied, Allah and His Messengerknow better. He said, That was Jibril (the Angel Gabriel). He came to teach you your religion. "},
    {id: 3, name: "Hadith 3", note: "Pillars of Islam", explanation: "	On the authority of Abdullah ibn Umar ibn Al-Khattab (R.A) who said: I heard the Messenger of Allah (S.A.W) say: Islam has been built on five pillars: testifying that there is no god but Allah and that Muhammad is the Messenger of Allah, performing the prayers, paying the Zakah, making the pilgrimage to the House, and fasting in Ramadan."},
    {id: 4, name: "Hadith 4", note: "Results of deeds depend on its last", explanation: "On the authority of Abdullah ibn Masud (R.A), who said: The Messenger of Allah (S.A.W), and he is the truthful and the believed, narrated to us: Verily the creation of each one of you is brought together in his mother's womb for forty days in the form of a drop, then he becomes a clot of blood for a like period, then a morsel of flesh for a like period, then there is sent to him the angel who blows the breath of life into him and who is commanded with four matters: to write down his sustenance, his life span, his actions, and whether he will be happy or unhappy (whether or not he will enter Paradise). By Allah, other than Whom there is no deity, verily one of you performs the actions of the people of Paradise until there is but an arm's length between him and it, and that which has been written overtakes him, and so he acts with the actions of the people of the Hellfire and thus enters it; and verily one of you performs the actions of the people of the Hellfire, until there is but an arm's length between him and it, and that which has been written overtakes him and so he acts with the actions of the people of Paradise and thus he enters it "},
    {id: 5, name: "Hadith 5", note: "Remove the innovation", explanation: "	On the authority of the mother of the faithful, 'Aisha (R.A), who said: The Messenger of Allah (S.A.W) said: He who innovates something in this matter of ours [Islam] that is not of it will have it rejected [by Allah]."},
    {id: 6, name:  "Hadith 6", note: "Lawful and unlawful things are cleared", explanation: "	On the authority of Abu 'Abdullah al-Nu'man bin Bashir (R.A) who said: I heard the Messenger of Allah(S.A.W) say: The halal is clear and the haram is clear, and between them are matters unclear that are unknown to most people. Whoever is wary of these unclear matters has absolved his religion and honor. And whoever indulges in them has indulged in the haram. It is like a shepherd who herds his sheep too close to preserved sanctuary, and they will eventually graze in it. Every king has a sanctuary, and the sanctuary of Allah is what He has made haram. There lies within the body a piece of flesh. If it is sound, the whole body is sound; and if it is corrupted, the whole body is corrupted. Verily this piece is the heart."},
    {id: 7, name:  "Hadith 7", note: "Religion is sincerity", explanation: "	On the authority of Tamim Al-Dari (R.A): The Prophet (S.A.W) said, The religion is naseehah (sincerity).We said, To whom? He (S.A.W) said, To Allah, His Book, His Messenger, and to the leaders of the Muslims and their common folk."},
    {id: 8, name:  "Hadith 8", note: "Protection of a muslim", explanation: "On the authority of Abdullah ibn Umar (R.A), the Messenger of Allah (S.A.W) said: I have been ordered to fight against the people until they testify that there is none worthy of worship except Allah and that Muhammad is the Messenger of Allah, and until they establish the Salah and pay the Zakah. And if they do so then they will have gained protection from me for their lives and property, unless [they commit acts that are punishable] in accordance to Islam, and their reckoning will be with Allah the Almighty."},
    {id: 9, name:  "Hadith 9", note: "Orders depend on ability", explanation: "On the authority of Abu Hurayrah (R.A) who said: I heard the Messenger of Allah (S.A.W) say: What I have forbidden for you, avoid. What I have ordered you [to do], do as much of it as you can. For verily, it was only their excessive questioning and disagreeing with their Prophets that destroyed [the nations] who were before you."},
    {id: 10, name: "Hadith 10", note: "To seek the good and lawful things", explanation: "	On the authority of Abu Hurayrah (R.A) who said: The Messenger of Allah (S.A.W) said: Allah the Almighty is good and accepts only that which is good. And verily Allah has commanded the believers to do that which He has commanded the Messengers. So the Almighty has said: O (you) Messengers! Eat of the tayyibat (good things), and perform righteous deeds [23:51] and the Almighty has said: O you who believe! Eat of the lawful things that We have provided you [2:172]. Then he (peace be upon him) mentioned a man who, having journeyed far, is dishevelled and dusty, and who spreads out his hands to the sky saying, O Lord! O Lord! while his food is haram, his drink is haram, his clothing is haram, and he has been nourished with haram, so how can [his supplication] be answered?"},
    {id: 11, name: "Hadith 11", note: "Leaving the doubtful things", explanation: "	On the authority of Abu Muhammad al-Hasan ibn Ali ibn Abee Talib (R.A), the grandson of the Messenger of Allah (S.A.W), and the one much loved by him, who said: I memorized from the Messenger of Allah (S.A.W): Leave what makes you doubtful for what does not."},
    {id: 12, name: "Hadith 12", note: "Leaving the unconcerned things", explanation: "	On the authority of Abu Hurayrah (R.A) who said: The Messenger of Allah (S.A.W) said: Part of the perfection of one's Islam is his leaving that which does not concern him."},
    {id: 13, name: "Hadith 13", note: "Perfection of faith", explanation: "	On the authority of Abu Hamzah Anas bin Malik (R.A) - the servant of the Messenger of Allah (S.A.W) - that the Prophet (S.A.W) said : None of you will believe until you love for your brother what you love for yourself."},
    {id: 14, name: "Hadith 14", note: "protection of muslims blood and its splitting", explanation: "	On the authority of Abdullah Ibn Masud (R.A) who said: The Messenger of Allah (S.A.W) said: It is not permissible to spill the blood of a Muslim except in three [instances]: the married person who commits adultery, a life for a life, and the one who forsakes his religion and separates from the community."},
    {id: 15, name: "Hadith 15", note: "Islamic manners", explanation: "On the authority of Abu Hurayrah (R.A), that the Messenger of Allah (S.A.W) said: Let him who believes in Allah and the Last Day speak good, or keep silent; and let him who believes in Allah and the Last Day be generous to his neighbour; and let him who believes in Allah and the Last Day be generous to his guest."},
    {id: 16, name: "Hadith 16", note: "Forbidding of angers", explanation: "	On the authority of Abu Hurayrah (R.A): A man said to the Prophet, Give me advice. The Prophet (S.A.W) said, Do not get angry. The man asked repeatedly and the Prophet answered each time, Do not get angry."},
    {id: 17, name: "Hadith 17", note: "proficiency in all things", explanation: "	On the authority of Abu Ya'la Shaddad bin Aws (R.A), that the Messenger of Allah(S.A.W) said: Verily Allah has prescribed ihsan (perfection) in all things. Thus if you kill, kill well; and if you slaughter, slaughter well. Let each one of you sharpen his blade and let him spare suffering to the animal he slaughters."},
    {id: 18, name: "Hadith 18", note: "Good behaving", explanation: "	On the authority of Abu Dharr Jundub ibn Junadah, and Abu 'Abd-ir-Rahman Mu'adh bin Jabal (R.A) that the Messenger of Allah (S.A.W) said: Be conscious of Allah wherever you are. Follow the bad deed with a good one to erase it, and engage others with beautiful character."},
    {id: 19, name: "Hadith 19", note: "Always remember Allah", explanation: "	Abu al-‘Abbas ‘Abdullah bin ‘Abbas (R.A) reports: One day I was riding (a horse/camel) behind the Prophet, (S.A.W), when he said, ‘Young man, I will teach you some words. Be mindful of God, and He will take care of you. Be mindful of Him, and you shall find Him at your side. If you ask, ask of God. If you need help, seek it from God. Know that if the whole world were to gather together in order to help you, they would not be able to help you except if God had written so. And if the whole world were to gather together in order to harm you, they would not harm you except if God had written so. The pens have been lifted, and the pages are dry."},
    {id: 20, name: "Hadith 20", note: "Shame is part of iman(belief)", explanation: "	Abu Mas'ud 'Uqbah bin 'Amr al-Ansari al-Badri (R.A) reported that the Messenger of Allah (S.A.W) said: ‘Among the early prophetic teachings that have reached people is this: if you do not feel shame, do what you wish."},
    {id: 21, name: "Hadith 21", note: "Beliefin Allah and remaining steadfast on it", explanation: "	On the authority of Sufyan bin Abdullah (R.A) who said: I said, 'O Messenger of Allah, tell me something about Islam which I can ask of no one but you.' He (S.A.W) said, 'Say I believe in Allah — and then be steadfast"},
    {id: 22, name: "Hadith 22", note: "Depending on obligatory deeds", explanation: "	On the authority of Abu Abdullah Jabir bin Abdullah al-Ansari (R.A): A man questioned the Messenger of Allah (S.A.W) and said: Do you think that if I perform the obligatory prayers, fast in Ramadan, treat as lawful that which is halal, and treat as forbidden that which is haram, and do not increase upon that [in voluntary good deeds], then I shall enter Paradise? He (S.A.W) replied, Yes."},
    {id: 23, name: "Hadith 23", note: "A guideline for a muslim", explanation: "	On the authority of Abu Malik al-Harith bin Asim al-Ashari (R.A) who said: The Messenger of Allah (S.A.W) said: Purity is half of Iman. Alhamdulillah (praise be to Allah) fills the scales, and subhan-Allah (how far from imperfection is Allah) and Alhamdulillah (praise be to Allah) fill that which is between heaven and earth. And the Salah (prayer) is a light, and charity is a proof, and patience is illumination, and the Qur'an is a proof either for you or against you. Every person starts his day as a vendor of his soul, either freeing it or bringing about its ruin."},
    {id: 24, name: "Hadith 24", note: "Forbidding of oppression", explanation: "	On the authority of Abu Dharr Al-Ghafari, of the Prophet (S.A.W) is that among the sayings he relates from his Lord is that He said: O My servants! I have forbidden oppression for Myself, and I have made it forbidden amongst you, so do not oppress one another. O My servants, all of you are astray except those whom I have guided, so seek guidance from Me and I shall guide you. O My servants, all of you are hungry except those whom I have fed, so seek food from Me and I shall feed you. O My servants, all of you are naked except those whom I have clothed, so seek clothing from Me and I shall clothe you. O My servants, you sommit sins by day and by night, and I forgive all sins, so seek forgiveness from Me and I shall forgive you. O My servants, you will not attain harming Me so as to harm Me, and you will not attain benefitting Me so as to benefit Me. O My servants, if the first of you and the last of you, and the humans of you and the jinn of you, were all as pious as the most pious heart of any individual amongst you, then this would not increase My Kingdom an iota. O My servants, if the first of you and the last of you, and the humans of you and the jinn of you, were all as wicked as the most wicked heart of any individual amongst you, then this would not decrease My Kingdom an iota. O My servants, if the first of you and the last of you, and the humans of you and the jinn of you, were all to stand together in one place and ask of Me, and I were to give everyone what he requested, then that would not decrease what I Possess, except what is decreased of the ocean when a needle is dipped into it. O My servants, it is but your deeds that I account for you, and then recompense you for. So he who finds good, let him praise Allah, and he who finds other than that, let him blame no one but himself."},
    {id: 25, name: "Hadith 25", note: "All actiion of a believers are charity", explanation: "	On the authority of Abu Dharr (R.A): Some people from amongst the Companions of the Messenger of Allah (S.A.W) said to the Prophet (S.A.W), 'O Messenger of Allah, the affluent have made off with the rewards; they pray as we pray, they fast as we fast, and they give [much] in charity by virtue of their wealth.' He (S.A.W) said, 'Has not Allah made things for you to give in charity? Truly every tasbeehah [saying subhan-Allah] is a charity, and every takbeerah [saying Allahu akbar] is a charity, and every tahmeedah [saying alhamdulillah] is a charity, and every tahleelah [saying la ilaha illAllah] is a charity. And commanding the good is a charity, and forbidding an evil is a charity, and in the sexual act of each one of you there is a charity.' They said, 'O Messenger of Allah, when one of us fulfills his sexual desire, will he have some reward for that?' He (S.A.W) said: 'Do you not see that if he were to act upon it [his desire] in an unlawful manner, then he would be deserving of punishment? Likewise, if he were to act upon it in a lawful manner, then he will be deserving of a reward."},
    {id: 26, name: "Hadith 26", note: "Minor act are valuable", explanation: "	Abu Hurairah (R.A) reported that the Messenger of Allah (S.A.W) said, Every joint of a person must perform a charity each day that the sun rises: to judge justly between two people is a charity. To help a man with his mount, lifting him onto it or hoisting up his belongings onto it, is a charity. And the good word is a charity. And every step that you take towards the prayer is a charity, and removing a harmful object from the road is a charity."},
    {id: 27, name: "Hadith 27", note: "Definition of righteousness", explanation: "	On the authority of an-Nawas bin Sam'an (R.A), the Prophet (S.A.W) said: Righteousness is in good character, and wrongdoing is that which wavers in your soul, and which you dislike people finding out about. And on the authority of Wabisah bin Ma'bad (R.A) who said, I came to the Messenger of Allah (S.A.W) and he (S.A.W) said, 'You have come to ask about righteousness.' I said, 'Yes.' He (S.A.W) said, 'Consult your heart. Righteousness is that about which the soul feels at ease and the heart feels tranquil. And wrongdoing is that which wavers in the soul and causes uneasiness in the breast, even though people have repeatedly given their legal opinion [in its favour]. A good hadeeth transmitted from the musnads of the two imams, Ahmed bin Hambal and Al-Darimi, with a good chain of authorities"},
    {id: 28, name: "Hadith 28", note: "must keep to the prophet sunnah", explanation: "	It was narrated on the authority of Abu Najih al-Irbad bin Sariyah (R.A) who said: The Messenger of Allah (S.A.W) delivered an admonition that made our hearts fearful and our eyes tearful. We said, O Messenger of Allah, it is as if this were a farewell sermon, so advise us. He said, I enjoin you to have Taqwa of Allah and that you listen and obey, even if a slave is made a ruler over you. He among you who lives long enough will see many differences. So for you is to observe my Sunnah and the Sunnah of the rightly-principled and rightly-guided successors, holding on to them with your molar teeth. Beware of newly-introduced matters, for every innovation (bid'ah) is an error."},
    {id: 29, name: "Hadith 29", note: "What deed admit you in paradise", explanation: "	On the authority of Muadh bin Jabal (R.A) who said: I said, 'O Messenger of Allah, tell me of an act which will take me into Paradise and will keep me away from the Hellfire.' He (S.A.W) said, 'You have asked me about a great matter, yet it is easy for him for whom Allah makes it easy. Worship Allah without associating any partners with Him; establish the prayer; pay the Zakah; fast in Ramadan; and make the pilgrimage to the House.Then he (S.A.W) said, 'Shall I not guide you towards the means of goodness? Fasting is a shield, charity wipes away sin as water extinguishes fire, and the praying of a man in the depths of the night.' Then he (S.A.W) recited: '[Those] who forsake their beds, to invoke their Lord in fear and hope, and they spend (charity in Allah's cause) out of what We have bestowed on them. No person knows what is kept hidden for them of joy as a reward for what they used to do' [as-Sajdah, 16-17]. Then he (S.A.W) said, 'Shall I not inform you of the head of the matter, its pillar and its peak?' I said, 'Yes, O Messenger of Allah.' He (S.A.W) said, 'The head of the matter is Islam, its pillar is the prayer and its peak is jihad.' Then he (S.A.W) said, 'Shall I not tell you of the foundation of all of that?' I said, 'Yes, O Messenger of Allah.' So he took hold of his tongue and said, 'Restrain this.' I said, 'O Prophet of Allah, will we be taken to account for what we say with it?' He (S.A.W) said, 'May your mother be bereaved of you, O Muadh! Is there anything that throws people into the Hellfire upon their faces, or on their noses, except the harvests of their tongues?"},
    {id: 30, name: "Hadith 30", note: "The limits set by Allah", explanation: "	On the authority of Jurthum bin Nashir (R.A) that the Messenger of Allah (S.A.W) said: Verily Allah the Almighty has laid down religious obligations (fara'id), so do not neglect them. He has set boundaries, so do not overstep them. He has prohibited some things, so do not violate them; about some things He was silent, out of compassion for you, not forgetfulness, so seek not after them."},
    {id: 31, name: "Hadith 31", note: "True renouncing", explanation: "	On the authority of Sahl bin Sa'ad al-Sa'idi (R.A) who said: A man came to the Prophet (S.A.W) and said: O Messenger of Allah, direct me to an act which, if I do it, [will cause] Allah to love me and the people to love me. So he (S.A.W) said, Renounce the world and Allah will love you, and renounce what people possess and the people will love you"},
    {id: 32, name: "Hadith 32", note: "Neither harming nor reciprocating harm", explanation: "	It was related on the authority of Abu Sa'id Sa'd bin Malik bin Sinan al-Khudri (R.A) that the Messenger of Allah (S.A.W) said: There should be neither harming nor reciprocating harm."},
    {id: 33, name: "Hadith 33", note: "Proof on claimant and oat upon denial", explanation: "	On the authority of Ibn Abbas (R.A), that the Messenger of Allah (S.A.W) said: Were people to be given everything that they claimed, men would [unjustly] claim the wealth and lives of [other] people. But, the onus of proof is upon the claimant, and the taking of an oath is upon him who denies."},
    {id: 34, name: "Hadith 34", note: "Forbiddeng the evil is part of iman", explanation: "	On the authority of Abu Sa’eed al-Khudree (R.A) who said: I heard the Messenger of Allah (S.A.W) say, “Whosoever of you sees an evil, let him change it with his hand; and if he is not able to do so, then [let him change it] with his tongue; and if he is not able to do so, then with his heart — and that is the weakest of faith.	On the authority of Abu Sa’eed al-Khudree (R.A) who said: I heard the Messenger of Allah (S.A.W) say, “Whosoever of you sees an evil, let him change it with his hand; and if he is not able to do so, then [let him change it] with his tongue; and if he is not able to do so, then with his heart — and that is the weakest of faith."},
    {id: 35, name: "Hadith 35", note: "Islamic brotherhood", explanation: " On the authority of Abu Hurayrah (R.A) who said: The Messenger of Allah (S.A.W) said, “Do not envy one another, and do not inflate prices for one another, and do not hate one another, and do not turn away from one another, and do not undercut one another in trade, but [rather] be slaves of Allah and brothers [amongst yourselves]. A Muslim is the brother of a Muslim: he does not oppress him, nor does he fail him, nor does he lie to him, nor does he hold him in contempt. Taqwa (piety) is right here [and he pointed to his chest three times]. It is evil enough for a man to hold his brother Muslim in contempt. The whole of a Muslim is inviolable for another Muslim: his blood, his property, and his honour."},
    {id: 36, name: "Hadith 36", note: "Allah help those who help others", explanation: "	On the authority of Abu Hurayrah (R.A), that the Prophet (S.A.W) said: Whoever removes a worldly grief from a believer, Allah will remove from him one of the griefs of the Day of Resurrection. And whoever alleviates the need of a needy person, Allah will alleviate his needs in this world and the Hereafter. Whoever shields [or hides the misdeeds of] a Muslim, Allah will shield him in this world and the Hereafter. And Allah will aid His slave so long as he aids his brother. And whoever follows a path to seek knowledge therein, Allah will make easy for him a path to Paradise. No people gather together in one of the Houses of Allah, reciting the Book of Allah and studying it among themselves, except that sakeenah (tranquility) descends upon them, and mercy envelops them, and the angels surround them, and Allah mentions them amongst those who are with Him. And whoever is slowed down by his actions, will not be hastened forward by his lineage."},
    {id: 37, name: "Hadith 37", note: "The compensation of Allah upon his slaves", explanation: "	On the authority of Ibn Abbas (R.A), from the Messenger of Allah (S.A.W), from what he has related from his Lord: Verily Allah ta’ala has written down the good deeds and the evil deeds, and then explained it [by saying]: Whosoever intended to perform a good deed, but did not do it, then Allah writes it down with Himself as a complete good deed. And if he intended to perform it and then did perform it, then Allah writes it down with Himself as from ten good deeds up to seven hundred times, up to many times multiplied. And if he intended to perform an evil deed, but did not do it, then Allah writes it down with Himself as a complete good deed. And if he intended it [i.e., the evil deed] and then performed it, then Allah writes it down as one evil deed."},
    {id: 38, name: "Hadith 38", note: "Approach Allah wuth Nawafil", explanation: "	On the authority of Abu Hurayrah (R.A) who said: The Messenger of Allah (S.A.W) said, Verily Allah ta’ala has said: Whosoever shows enmity to a wali (friend) of Mine, then I have declared war against him. And My servant does not draw near to Me with anything more loved to Me than the religious duties I have obligated upon him. And My servant continues to draw near to me with nafil (supererogatory) deeds until I Love him. When I Love him, I am his hearing with which he hears, and his sight with which he sees, and his hand with which he strikes, and his foot with which he walks. Were he to ask [something] of Me, I would surely give it to him; and were he to seek refuge with Me, I would surely grant him refuge."},
    {id: 39, name: "Hadith 39", note: "pardoning of mistakes and forgetfulness", explanation: "	On the authority of Ibn Abbas (R.A), the Messenger of Allah (S.A.w) said: Verily Allah has pardoned for me my ummah: their mistakes, their forgetfulness, and that which they have been forced to do under duress."},
    {id: 40, name: "Hadith 40", note: "The Life of this world", explanation: "	On the authority of Abdullah ibn Umar (R.A), who said: The Messenger of Allah (S.A.W) took me by the shoulder and said, Be in this world as though you were a stranger or a wayfarer.” And Ibn Umar (R.A) used to say, In the evening do not expect [to live until] the morning, and in the morning do not expect [to live until] the evening. Take [advantage of] your health before times of sickness, and [take advantage of] your life before your death."},
    {id: 41, name: "Hadith 41", note: "Follow up what the prophet has brought", explanation: "	On the authority of Abu Muhammad Abdullah bin ’Amr bin al-’Aas (R.A) who said: The Messenger of Allah (S.A.W) said, None of you [truly] believes until his desires are subservient to that which I have brought."},
//    {id: 40, name: "Hadith 1", note: "Deed depends on intention"},
    {id: 42, name: "Hadith 42", note: "Allah is All-forgiving", explanation: "	On the authority of Anas (R.A) who said: I heard the Messenger of Allah (S.A.W) say, Allah the Almighty has said: ‘O Son of Adam, as long as you invoke Me and ask of Me, I shall forgive you for what you have done, and I shall not mind. O Son of Adam, were your sins to reach the clouds of the sky and you then asked forgiveness from Me, I would forgive you. O Son of Adam, were you to come to Me with sins nearly as great as the Earth, and were you then to face Me, ascribing no partner to Me, I would bring you forgiveness nearly as great as it [too]."})
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad RobanaPage');
  }

  viewDetails($event, item){
    this.navCtrl.push(RobanaDetailsPage, item)
  }

  goToInfo(){
  }
}
